/********************************************************************
* MCEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MCEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableMCEventDict();
extern void G__cpp_setup_inheritanceMCEventDict();
extern void G__cpp_setup_typetableMCEventDict();
extern void G__cpp_setup_memvarMCEventDict();
extern void G__cpp_setup_globalMCEventDict();
extern void G__cpp_setup_memfuncMCEventDict();
extern void G__cpp_setup_funcMCEventDict();
extern void G__set_cpp_environmentMCEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/coda/coda/2.5/Linux/bin/tunl_soft/source/include/MCEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MCEventDictLN_TClass;
extern G__linked_taginfo G__MCEventDictLN_TBuffer;
extern G__linked_taginfo G__MCEventDictLN_TMemberInspector;
extern G__linked_taginfo G__MCEventDictLN_TObject;
extern G__linked_taginfo G__MCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MCEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCEventDictLN_TString;
extern G__linked_taginfo G__MCEventDictLN_TClonesArray;
extern G__linked_taginfo G__MCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MCEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MCEventDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MCEventDictLN_TVector3;
extern G__linked_taginfo G__MCEventDictLN_DetectorHit;
extern G__linked_taginfo G__MCEventDictLN_TargetHit;
extern G__linked_taginfo G__MCEventDictLN_EventPrimary;
extern G__linked_taginfo G__MCEventDictLN_MCEvent;

/* STUB derived class for protected member access */
