# Things common to both library and executable builds live in Makefile.common
include $(RELEASE_CMS)/Makefile.common

LD = $(CXX)

ifdef DEBUG
  LD_FLAGS += -g -pg
endif


ifndef EXENAME
  EXENAME = $(MODULE_NAME)$(DEBUG_SUFFIX)
endif

VPATH = $(RELEASE_LIB)
LD_DIRS = $(addprefix -L,$(RELEASE_SLIB))

LD_LIBS = $(addsuffix $(DEBUG_SUFFIX),$(MODULES))

BINARY = $(RELEASE_BIN)/$(EXENAME)

.PHONY:  mkbindir

all: mklib mkbin

mklib: mklibdir 

mkbin: mkbindir $(BINARY)

$(BINARY): $(OBJS)
	   $(LD) $(LD_FLAGS) $(LD_DIRS) $(LD_LIBS) $(OBJS) -o $@

mkbindir:
	@mkdir -p $(RELEASE_BIN)

clean:
	rm -f $(BINARY) $(SLIBNAME) *.o *.bak *~ #*#
	rm -rf depends/$(OSNAME)

env:
	@echo CC		= $(CC)
	@echo CXX		= $(CXX)
	@echo LD		= $(LD)
	@echo LD_LIBS		= $(LD_LIBS)
	@echo LD_DIRS		= $(LD_DIRS)
	@echo CFLAGS    	= $(CFLAGS)
	@echo CXXFLAGS  	= $(CXXFLAGS)
	@echo CSRC		= $(CSRC)
	@echo CXXSRC    	= $(CXXSRC)
	@echo LIBS		= $(LIBS)
	@echo OSNAME    	= $(OSNAME)
	@echo OBJS		= $(OBJS)
	@echo EXENAME   	= $(EXENAME)
	@echo ROOTGLIBS         = $(ROOTGLIBS)
	@echo VPATH             = $(VPATH)

include $(RELEASE_CMS)/Makefile.common.rules






