/********************************************************************
* DataStructureDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DataStructureDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableDataStructureDict();
extern void G__cpp_setup_inheritanceDataStructureDict();
extern void G__cpp_setup_typetableDataStructureDict();
extern void G__cpp_setup_memvarDataStructureDict();
extern void G__cpp_setup_globalDataStructureDict();
extern void G__cpp_setup_memfuncDataStructureDict();
extern void G__cpp_setup_funcDataStructureDict();
extern void G__set_cpp_environmentDataStructureDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/coda/coda/2.5/Linux/bin/tunl_soft/source/include/DataStructure.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataStructureDictLN_TClass;
extern G__linked_taginfo G__DataStructureDictLN_TBuffer;
extern G__linked_taginfo G__DataStructureDictLN_TMemberInspector;
extern G__linked_taginfo G__DataStructureDictLN_TObject;
extern G__linked_taginfo G__DataStructureDictLN_TNamed;
extern G__linked_taginfo G__DataStructureDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataStructureDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataStructureDictLN_TString;
extern G__linked_taginfo G__DataStructureDictLN_TClonesArray;
extern G__linked_taginfo G__DataStructureDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DataStructureDictLN_RunInfo;
extern G__linked_taginfo G__DataStructureDictLN_RunControlEvent;
extern G__linked_taginfo G__DataStructureDictLN_HardwareData;
extern G__linked_taginfo G__DataStructureDictLN_RawData;

/* STUB derived class for protected member access */
